### ISSUE TITLE
licence is not declared

### ISSUE THREAD

**Issue by ferriswheel** [quentinsf/icsv2ledger#133]
hello,

please specify a licence for this project so i can legally use this code.

regards

**Comment by quentinsf** [comment]
Hi there - 

Ah, yes, sorry - I never put one on here at the start, and others have contributed a great deal since then, so in theory I shouldn't impose one at this stage. However...

As the original creator of icsv2ledger I hereby declare that it is available under the GNU General Public License v2, unless any more recent contributor declares before the end of Sept 2019 that they would prefer another licence.

Assuming nobody objects, we can add a proper licence file then.
